[tool.poetry]
name = "insdc-benchmarking-scripts"
version = "0.1.0"
description = "Benchmarking scripts for INSDC data transfers"
authors = ["Australian BioCommons <guerdon@biocommons.org.au>"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
insdc-benchmarking-schema = "^1.2.0"
requests = "^2.31.0"
click = "^8.1.0"
psutil = "^5.9.0"
pyyaml = "^6.0.0"
certifi = "^2025.10.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.12.0"
ruff = "^0.1.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
